# Generated by Django 4.1.5 on 2023-01-12 10:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('owl_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author_name', models.CharField(help_text='Full name of author', max_length=200)),
                ('type', models.CharField(blank=True, choices=[('pb', 'PAPERBACK'), ('hc', 'HARDCOVER'), ('hm', 'HANDMADE'), ('nd', 'NOTDEFINED')], default='nd', help_text='Book type', max_length=2)),
                ('is_borrowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('email', models.EmailField(editable=False, max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookBorrower',
            fields=[
                ('book_borrower_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrower_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.borrower')),
            ],
        ),
    ]
