# Generated by Django 4.1.5 on 2023-01-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='book_copy_type',
            field=models.CharField(blank=True, choices=[('pb', 'PAPERBACK'), ('hc', 'HARDCOVER'), ('hm', 'HANDMADE'), ('nd', 'NOTDEFINED')], default='nd', max_length=2),
        ),
    ]
