# Generated by Django 4.1.5 on 2023-01-12 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_borrower_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrower',
            name='book_owl_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.book'),
        ),
        migrations.AddField(
            model_name='bookborrower',
            name='borrow_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookborrower',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookborrower',
            name='next_borrow_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookborrower',
            name='borrower_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.borrower'),
        ),
    ]
