# Generated by Django 4.1.5 on 2023-01-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_bookcopy_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='book_copy_type',
            field=models.CharField(choices=[('pb', 'PAPERBACK'), ('hc', 'HARDCOVER'), ('hm', 'HANDMADE')], max_length=2),
        ),
    ]
