# Generated by Django 4.1.5 on 2023-01-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_alter_book_type_alter_bookborrower_book_owl_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookborrower',
            old_name='borrower_email',
            new_name='borrower',
        ),
        migrations.RemoveField(
            model_name='bookborrower',
            name='book_owl_id',
        ),
        migrations.AddField(
            model_name='bookborrower',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(blank=True, choices=[('pb', 'PAPERBACK'), ('hc', 'HARDCOVER'), ('hm', 'HANDMADE'), ('nd', 'NOTDEFINED')], default='nd', help_text='Book type', max_length=2, verbose_name='book type'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='username',
            field=models.CharField(max_length=200, verbose_name='user name'),
        ),
    ]
