# Generated by Django 4.1.5 on 2023-01-15 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_alter_bookcopy_book_copy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='base_app.book'),
        ),
    ]
